-- 021: 添加 SCHEDULE_INVITE 消息类型
-- 用于 V4 日程邀请卡片（draft_invite → confirm 发送）
ALTER TABLE messages
    MODIFY COLUMN type ENUM('TEXT','AVAILABILITY_CARD','CONFIRM_REQUEST','CONFIRM_RESPONSE','SCHEDULE_INVITE') NOT NULL;
